services:
  web:
    build: .
    ports:
      - "1443:1443"
    environment:
      - REDIS_HOST=redis
      - DETECT_BASE_URL=true
      - FILE_DIR=/uploads
      - UI_COLOR_PRIMARY=#e7af07
      - UI_COLOR_ACCENT=#c89506
    volumes:
      - ./uploads:/uploads
    depends_on:
      - redis
  redis:
    image: redis:alpine
  selenium-firefox:
    image: b4handjr/selenium-firefox
    ports:
      - "${VNC_PORT:-5900}:5900"
    shm_size: 2g
    volumes:
      - .:/code
